/* Copyright (c) 2004, University of Oslo, Norway
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 *  * Neither the name of the University of Oslo nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *      
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.vortikal.web.service;

import org.vortikal.repository.Resource;
import org.vortikal.security.Principal;


/**
 * An Assertion states a fact about something. The only thing assertions share, 
 * are the ability to check if there is a known conflict between this and 
 * another assertion. Subinterfaces specifies the actual matching of the 
 * assertions.
 *
 * <p>Assertions can also have an effect on URLs generated by the
 * framework (see {@link Service#constructLink}), such as the request
 * hostname, port, protocol, querystring and other parameters. For
 * example, an assertion stating that "The URL must contain request
 * parameter <code>foo=bar</code>" should ensure that this parameter
 * exists in the generated URL's query string when the
 * <code>processURL()</code> method is called.
 */
public interface Assertion {


    /**
     * Contributes to the construction of a URL. Assertions may
     * "decorate" a URL in many ways, for instance changing the port
     * number, query parameters, etc.
     *
     * @param url the URL that is in the process of being constructed.
     * @param resource the resorurce for which the URL is being
     * constructed
     * @param principal the authenticated principal for which the URL
     * is being constructed
     */
    public void processURL(URL url, Resource resource, Principal principal);



    /**
     * Decides whether this assertion is in conflict with another
     * assertion. 
     * 
     * @param assertion the assertion for which to check conflict
     * @return <code>true</code> if the two assertions are
     * incompatible, <code>false</code> otherwise.
     */
    public boolean conflicts(Assertion assertion);

    

}
